version: '3'
services:
  # watch2gther:
  #   image: robrotheram/watch2gether:v0.1.1
  #   container_name: watch2gether
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: any
  #   ports:
  #     - 3000:8080

  rethinkdb:
    image: rethinkdb
    ports:
     - "28015:28015"
     - "8082:8080"
    volumes:
     - /data:/data
    command: rethinkdb --bind all