version: '3'
services:
  watch2gther:
    image: mohitpundir28/watch2gether:latest
    container_name: watch2gether
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - ${PWD}/data:/data
    environment: 
      - DATABASE_PATH=/data
      - DISCORD_TOKEN=
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=
      - SESSION_SECRET=
      - BASE_URL=http://localhost:8080
      - DEVELOPMENT=false 
      - DISCORD_ENABLE_NOTIFICATIONS=false
    ports:
      - 3000:8080