version: '3'
services:
  watch2gther:
    image: robrotheram/watch2gether:v0.2
    container_name: watch2gether
    depends_on: 
      - rethinkdb
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - 3000:8080

  rethinkdb:
    image: rethinkdb
    hostname: rethinkdb
    volumes:
     - /data:/data
    command: rethinkdb --bind all